//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfUnsignedLong", Namespace="http://web.cbr.ru/", ItemName="unsignedLong")]
    public class ArrayOfUnsignedLong : System.Collections.Generic.List<ulong>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataItem", Namespace="http://web.cbr.ru/")]
    public partial class DataItem : object
    {
        
        private ulong IDField;
        
        private string CodeField;
        
        private string NameField;
        
        private string SNameField;
        
        private ulong INNField;
        
        private ulong OGRNField;
        
        private string DataField;
        
        private System.DateTime LastUpdateField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ulong ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SName
        {
            get
            {
                return this.SNameField;
            }
            set
            {
                this.SNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public ulong INN
        {
            get
            {
                return this.INNField;
            }
            set
            {
                this.INNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public ulong OGRN
        {
            get
            {
                return this.OGRNField;
            }
            set
            {
                this.OGRNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime LastUpdate
        {
            get
            {
                return this.LastUpdateField;
            }
            set
            {
                this.LastUpdateField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://web.cbr.ru/", ConfigurationName="ServiceReference1.rcbwsSoap")]
    public interface rcbwsSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetLastUpdate", ReplyAction="*")]
        System.Threading.Tasks.Task<System.DateTime> GetLastUpdateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/TotalPages", ReplyAction="*")]
        System.Threading.Tasks.Task<int> TotalPagesAsync(System.DateTime dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetIDsAfter", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetIDsAfterResponse> GetIDsAfterAsync(ServiceReference1.GetIDsAfterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetDataAfter", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetDataAfterResponse> GetDataAfterAsync(ServiceReference1.GetDataAfterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetDataRange", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetDataRangeResponse> GetDataRangeAsync(ServiceReference1.GetDataRangeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetDataByINN", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetDataByINNResponse> GetDataByINNAsync(ServiceReference1.GetDataByINNRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetDataByOGRN", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetDataByOGRNResponse> GetDataByOGRNAsync(ServiceReference1.GetDataByOGRNRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetDataByCode", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetDataByCodeResponse> GetDataByCodeAsync(ServiceReference1.GetDataByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetDataById", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetDataByIdResponse> GetDataByIdAsync(ServiceReference1.GetDataByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/SearchByName", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.SearchByNameResponse> SearchByNameAsync(ServiceReference1.SearchByNameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIDsAfterRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIDsAfter", Namespace="http://web.cbr.ru/", Order=0)]
        public ServiceReference1.GetIDsAfterRequestBody Body;
        
        public GetIDsAfterRequest()
        {
        }
        
        public GetIDsAfterRequest(ServiceReference1.GetIDsAfterRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://web.cbr.ru/")]
    public partial class GetIDsAfterRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime dt;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Page;
        
        public GetIDsAfterRequestBody()
        {
        }
        
        public GetIDsAfterRequestBody(System.DateTime dt, int Page)
        {
            this.dt = dt;
            this.Page = Page;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIDsAfterResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIDsAfterResponse", Namespace="http://web.cbr.ru/", Order=0)]
        public ServiceReference1.GetIDsAfterResponseBody Body;
        
        public GetIDsAfterResponse()
        {
        }
        
        public GetIDsAfterResponse(ServiceReference1.GetIDsAfterResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://web.cbr.ru/")]
    public partial class GetIDsAfterResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.ArrayOfUnsignedLong GetIDsAfterResult;
        
        public GetIDsAfterResponseBody()
        {
        }
        
        public GetIDsAfterResponseBody(ServiceReference1.ArrayOfUnsignedLong GetIDsAfterResult)
        {
            this.GetIDsAfterResult = GetIDsAfterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataAfterRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataAfter", Namespace="http://web.cbr.ru/", Order=0)]
        public ServiceReference1.GetDataAfterRequestBody Body;
        
        public GetDataAfterRequest()
        {
        }
        
        public GetDataAfterRequest(ServiceReference1.GetDataAfterRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://web.cbr.ru/")]
    public partial class GetDataAfterRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime dt;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Page;
        
        public GetDataAfterRequestBody()
        {
        }
        
        public GetDataAfterRequestBody(System.DateTime dt, int Page)
        {
            this.dt = dt;
            this.Page = Page;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataAfterResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataAfterResponse", Namespace="http://web.cbr.ru/", Order=0)]
        public ServiceReference1.GetDataAfterResponseBody Body;
        
        public GetDataAfterResponse()
        {
        }
        
        public GetDataAfterResponse(ServiceReference1.GetDataAfterResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://web.cbr.ru/")]
    public partial class GetDataAfterResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.DataItem[] GetDataAfterResult;
        
        public GetDataAfterResponseBody()
        {
        }
        
        public GetDataAfterResponseBody(ServiceReference1.DataItem[] GetDataAfterResult)
        {
            this.GetDataAfterResult = GetDataAfterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataRangeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataRange", Namespace="http://web.cbr.ru/", Order=0)]
        public ServiceReference1.GetDataRangeRequestBody Body;
        
        public GetDataRangeRequest()
        {
        }
        
        public GetDataRangeRequest(ServiceReference1.GetDataRangeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://web.cbr.ru/")]
    public partial class GetDataRangeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.ArrayOfUnsignedLong IDs;
        
        public GetDataRangeRequestBody()
        {
        }
        
        public GetDataRangeRequestBody(ServiceReference1.ArrayOfUnsignedLong IDs)
        {
            this.IDs = IDs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataRangeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataRangeResponse", Namespace="http://web.cbr.ru/", Order=0)]
        public ServiceReference1.GetDataRangeResponseBody Body;
        
        public GetDataRangeResponse()
        {
        }
        
        public GetDataRangeResponse(ServiceReference1.GetDataRangeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://web.cbr.ru/")]
    public partial class GetDataRangeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.DataItem[] GetDataRangeResult;
        
        public GetDataRangeResponseBody()
        {
        }
        
        public GetDataRangeResponseBody(ServiceReference1.DataItem[] GetDataRangeResult)
        {
            this.GetDataRangeResult = GetDataRangeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataByINNRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataByINN", Namespace="http://web.cbr.ru/", Order=0)]
        public ServiceReference1.GetDataByINNRequestBody Body;
        
        public GetDataByINNRequest()
        {
        }
        
        public GetDataByINNRequest(ServiceReference1.GetDataByINNRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://web.cbr.ru/")]
    public partial class GetDataByINNRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public ulong INN;
        
        public GetDataByINNRequestBody()
        {
        }
        
        public GetDataByINNRequestBody(ulong INN)
        {
            this.INN = INN;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataByINNResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataByINNResponse", Namespace="http://web.cbr.ru/", Order=0)]
        public ServiceReference1.GetDataByINNResponseBody Body;
        
        public GetDataByINNResponse()
        {
        }
        
        public GetDataByINNResponse(ServiceReference1.GetDataByINNResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://web.cbr.ru/")]
    public partial class GetDataByINNResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.DataItem[] GetDataByINNResult;
        
        public GetDataByINNResponseBody()
        {
        }
        
        public GetDataByINNResponseBody(ServiceReference1.DataItem[] GetDataByINNResult)
        {
            this.GetDataByINNResult = GetDataByINNResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataByOGRNRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataByOGRN", Namespace="http://web.cbr.ru/", Order=0)]
        public ServiceReference1.GetDataByOGRNRequestBody Body;
        
        public GetDataByOGRNRequest()
        {
        }
        
        public GetDataByOGRNRequest(ServiceReference1.GetDataByOGRNRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://web.cbr.ru/")]
    public partial class GetDataByOGRNRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public ulong OGRN;
        
        public GetDataByOGRNRequestBody()
        {
        }
        
        public GetDataByOGRNRequestBody(ulong OGRN)
        {
            this.OGRN = OGRN;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataByOGRNResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataByOGRNResponse", Namespace="http://web.cbr.ru/", Order=0)]
        public ServiceReference1.GetDataByOGRNResponseBody Body;
        
        public GetDataByOGRNResponse()
        {
        }
        
        public GetDataByOGRNResponse(ServiceReference1.GetDataByOGRNResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://web.cbr.ru/")]
    public partial class GetDataByOGRNResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.DataItem[] GetDataByOGRNResult;
        
        public GetDataByOGRNResponseBody()
        {
        }
        
        public GetDataByOGRNResponseBody(ServiceReference1.DataItem[] GetDataByOGRNResult)
        {
            this.GetDataByOGRNResult = GetDataByOGRNResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataByCodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataByCode", Namespace="http://web.cbr.ru/", Order=0)]
        public ServiceReference1.GetDataByCodeRequestBody Body;
        
        public GetDataByCodeRequest()
        {
        }
        
        public GetDataByCodeRequest(ServiceReference1.GetDataByCodeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://web.cbr.ru/")]
    public partial class GetDataByCodeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Code;
        
        public GetDataByCodeRequestBody()
        {
        }
        
        public GetDataByCodeRequestBody(string Code)
        {
            this.Code = Code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataByCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataByCodeResponse", Namespace="http://web.cbr.ru/", Order=0)]
        public ServiceReference1.GetDataByCodeResponseBody Body;
        
        public GetDataByCodeResponse()
        {
        }
        
        public GetDataByCodeResponse(ServiceReference1.GetDataByCodeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://web.cbr.ru/")]
    public partial class GetDataByCodeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.DataItem[] GetDataByCodeResult;
        
        public GetDataByCodeResponseBody()
        {
        }
        
        public GetDataByCodeResponseBody(ServiceReference1.DataItem[] GetDataByCodeResult)
        {
            this.GetDataByCodeResult = GetDataByCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataByIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataById", Namespace="http://web.cbr.ru/", Order=0)]
        public ServiceReference1.GetDataByIdRequestBody Body;
        
        public GetDataByIdRequest()
        {
        }
        
        public GetDataByIdRequest(ServiceReference1.GetDataByIdRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://web.cbr.ru/")]
    public partial class GetDataByIdRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public ulong id;
        
        public GetDataByIdRequestBody()
        {
        }
        
        public GetDataByIdRequestBody(ulong id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataByIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataByIdResponse", Namespace="http://web.cbr.ru/", Order=0)]
        public ServiceReference1.GetDataByIdResponseBody Body;
        
        public GetDataByIdResponse()
        {
        }
        
        public GetDataByIdResponse(ServiceReference1.GetDataByIdResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://web.cbr.ru/")]
    public partial class GetDataByIdResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.DataItem GetDataByIdResult;
        
        public GetDataByIdResponseBody()
        {
        }
        
        public GetDataByIdResponseBody(ServiceReference1.DataItem GetDataByIdResult)
        {
            this.GetDataByIdResult = GetDataByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchByNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchByName", Namespace="http://web.cbr.ru/", Order=0)]
        public ServiceReference1.SearchByNameRequestBody Body;
        
        public SearchByNameRequest()
        {
        }
        
        public SearchByNameRequest(ServiceReference1.SearchByNameRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://web.cbr.ru/")]
    public partial class SearchByNameRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Name;
        
        public SearchByNameRequestBody()
        {
        }
        
        public SearchByNameRequestBody(string Name)
        {
            this.Name = Name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchByNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchByNameResponse", Namespace="http://web.cbr.ru/", Order=0)]
        public ServiceReference1.SearchByNameResponseBody Body;
        
        public SearchByNameResponse()
        {
        }
        
        public SearchByNameResponse(ServiceReference1.SearchByNameResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://web.cbr.ru/")]
    public partial class SearchByNameResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.DataItem[] SearchByNameResult;
        
        public SearchByNameResponseBody()
        {
        }
        
        public SearchByNameResponseBody(ServiceReference1.DataItem[] SearchByNameResult)
        {
            this.SearchByNameResult = SearchByNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface rcbwsSoapChannel : ServiceReference1.rcbwsSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class rcbwsSoapClient : System.ServiceModel.ClientBase<ServiceReference1.rcbwsSoap>, ServiceReference1.rcbwsSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public rcbwsSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(rcbwsSoapClient.GetBindingForEndpoint(endpointConfiguration), rcbwsSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public rcbwsSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(rcbwsSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public rcbwsSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(rcbwsSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public rcbwsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<System.DateTime> GetLastUpdateAsync()
        {
            return base.Channel.GetLastUpdateAsync();
        }
        
        public System.Threading.Tasks.Task<int> TotalPagesAsync(System.DateTime dt)
        {
            return base.Channel.TotalPagesAsync(dt);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetIDsAfterResponse> ServiceReference1.rcbwsSoap.GetIDsAfterAsync(ServiceReference1.GetIDsAfterRequest request)
        {
            return base.Channel.GetIDsAfterAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetIDsAfterResponse> GetIDsAfterAsync(System.DateTime dt, int Page)
        {
            ServiceReference1.GetIDsAfterRequest inValue = new ServiceReference1.GetIDsAfterRequest();
            inValue.Body = new ServiceReference1.GetIDsAfterRequestBody();
            inValue.Body.dt = dt;
            inValue.Body.Page = Page;
            return ((ServiceReference1.rcbwsSoap)(this)).GetIDsAfterAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetDataAfterResponse> ServiceReference1.rcbwsSoap.GetDataAfterAsync(ServiceReference1.GetDataAfterRequest request)
        {
            return base.Channel.GetDataAfterAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetDataAfterResponse> GetDataAfterAsync(System.DateTime dt, int Page)
        {
            ServiceReference1.GetDataAfterRequest inValue = new ServiceReference1.GetDataAfterRequest();
            inValue.Body = new ServiceReference1.GetDataAfterRequestBody();
            inValue.Body.dt = dt;
            inValue.Body.Page = Page;
            return ((ServiceReference1.rcbwsSoap)(this)).GetDataAfterAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetDataRangeResponse> ServiceReference1.rcbwsSoap.GetDataRangeAsync(ServiceReference1.GetDataRangeRequest request)
        {
            return base.Channel.GetDataRangeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetDataRangeResponse> GetDataRangeAsync(ServiceReference1.ArrayOfUnsignedLong IDs)
        {
            ServiceReference1.GetDataRangeRequest inValue = new ServiceReference1.GetDataRangeRequest();
            inValue.Body = new ServiceReference1.GetDataRangeRequestBody();
            inValue.Body.IDs = IDs;
            return ((ServiceReference1.rcbwsSoap)(this)).GetDataRangeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetDataByINNResponse> ServiceReference1.rcbwsSoap.GetDataByINNAsync(ServiceReference1.GetDataByINNRequest request)
        {
            return base.Channel.GetDataByINNAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetDataByINNResponse> GetDataByINNAsync(ulong INN)
        {
            ServiceReference1.GetDataByINNRequest inValue = new ServiceReference1.GetDataByINNRequest();
            inValue.Body = new ServiceReference1.GetDataByINNRequestBody();
            inValue.Body.INN = INN;
            return ((ServiceReference1.rcbwsSoap)(this)).GetDataByINNAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetDataByOGRNResponse> ServiceReference1.rcbwsSoap.GetDataByOGRNAsync(ServiceReference1.GetDataByOGRNRequest request)
        {
            return base.Channel.GetDataByOGRNAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetDataByOGRNResponse> GetDataByOGRNAsync(ulong OGRN)
        {
            ServiceReference1.GetDataByOGRNRequest inValue = new ServiceReference1.GetDataByOGRNRequest();
            inValue.Body = new ServiceReference1.GetDataByOGRNRequestBody();
            inValue.Body.OGRN = OGRN;
            return ((ServiceReference1.rcbwsSoap)(this)).GetDataByOGRNAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetDataByCodeResponse> ServiceReference1.rcbwsSoap.GetDataByCodeAsync(ServiceReference1.GetDataByCodeRequest request)
        {
            return base.Channel.GetDataByCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetDataByCodeResponse> GetDataByCodeAsync(string Code)
        {
            ServiceReference1.GetDataByCodeRequest inValue = new ServiceReference1.GetDataByCodeRequest();
            inValue.Body = new ServiceReference1.GetDataByCodeRequestBody();
            inValue.Body.Code = Code;
            return ((ServiceReference1.rcbwsSoap)(this)).GetDataByCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetDataByIdResponse> ServiceReference1.rcbwsSoap.GetDataByIdAsync(ServiceReference1.GetDataByIdRequest request)
        {
            return base.Channel.GetDataByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetDataByIdResponse> GetDataByIdAsync(ulong id)
        {
            ServiceReference1.GetDataByIdRequest inValue = new ServiceReference1.GetDataByIdRequest();
            inValue.Body = new ServiceReference1.GetDataByIdRequestBody();
            inValue.Body.id = id;
            return ((ServiceReference1.rcbwsSoap)(this)).GetDataByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.SearchByNameResponse> ServiceReference1.rcbwsSoap.SearchByNameAsync(ServiceReference1.SearchByNameRequest request)
        {
            return base.Channel.SearchByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.SearchByNameResponse> SearchByNameAsync(string Name)
        {
            ServiceReference1.SearchByNameRequest inValue = new ServiceReference1.SearchByNameRequest();
            inValue.Body = new ServiceReference1.SearchByNameRequestBody();
            inValue.Body.Name = Name;
            return ((ServiceReference1.rcbwsSoap)(this)).SearchByNameAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.rcbwsSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.rcbwsSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.rcbwsSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://www.cbr.ru/ecbwebserv/rcbws.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.rcbwsSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://www.cbr.ru/ecbwebserv/rcbws.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            rcbwsSoap,
            
            rcbwsSoap12,
        }
    }
}
